---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install system packages
  ansible.builtin.apt:
    pkg:
      - ninja-build
      - software-properties-common
      - gettext
      - curl
      - wget
      - git
      - dnsutils
      - ripgrep
      - fzf
      - zsh
      - python3.10
      - python3-pip
      - unzip
      - clang
      - gcc
      - cmake
      - libssl-dev
      - tmux
      - jq
      - htop
      - redis-server
      - postgresql
      - openssh-server
      - openssh-client
      - gh
      - direnv
      - neofetch

- name: Clone tmux-plugins/tpm to /root/.tmux/plugins/tpm
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: '/root/.tmux/plugins/tpm'

- name: Install tmux plugins
  command: /root/.tmux/plugins/tpm/bin/install_plugins

- name: Clone neovim/neovim and install
  shell:
    cmd: |
      git clone https://github.com/neovim/neovim
      cd neovim
      make CMAKE_BUILD_TYPE=RelWithDebInfo
      make install
      cd ..
      rm -rf neovim

- name: Change default shell to zsh
  user:
    name: root
    shell: /usr/bin/zsh

- name: Execute go-install.sh
  shell:
    cmd: |
      bash /root/go-install.sh

- name: Clone lucagez/patman and install
  shell:
    cmd: |
      source /root/.zshrc
      git clone https://github.com/lucagez/patman
      cd patman
      make patman
      cp build/patman /usr/local/bin
      go clean -cache -modcache -i -r
      cd ..
      rm -rf patman

- name: Install Node.js version manager
  shell:
    cmd: curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell

- name: Install Node.js 18
  shell:
    cmd: |
      /root/.local/share/fnm/fnm install 18

- name: Install croc file transfer
  shell:
    cmd: curl https://getcroc.schollz.com | bash

- name: Execute ssh_init
  shell:
    cmd: |
      chmod +x /usr/local/bin/ssh_init
      ssh_init root

- name: Install neovim plugins
  shell:
    cmd: nvim --headless "+Lazy! sync" +qa

- name: Clean up APT
  apt:
    autoclean: yes

- name: Remove APT cache files
  command: apt-get clean

- name: Remove unused dependencies
  command: apt-get autoremove --yes

- name: Remove unnecessary packages
  shell:
    cmd: |
      DEBIAN_FRONTEND=noninteractive apt-get purge -y \
      $(dpkg --list | grep "^rc" | awk '{print $2}')
